### PR TITLE
Moved to Sass and updated styles

### PR DESCRIPTION
**Pull request by RyanDeegan**
Moved to Sass, added keyboard functionality, changed styles a bit to work full screen across different devices.

### CODE REVIEW

**Comment by RyanDeegan** [comment]
https://ryandeegan.github.io/Swearing-Xylophone/

**Comment by yoshi-city** [comment]
maybe drop the keyboard functionality part

**Comment by RyanDeegan** [comment]
> maybe drop the keyboard functionality part

Hmm. I think keyboard-only users would appreciate a swearing xylophone. Comes as a standard when moving to the semantic buttons markup anyway.

**Comment by yoshi-city** [comment]
I did the keyboard functionality too, Limmy's response to my pull request:

> Sorry but I'm not going to include this, I just want it to be clicked or touched. Plus nobody would know you can use the number keys unless I put some words below the xylophone, and I don't want the clutter. My apologies!

**Comment by thomaswoodcock** [comment]
Isn't adding Sass and a build step a bit unnecessary for such a tiny project?

**Comment by RyanDeegan** [comment]
> Isn't adding Sass and a build step a bit unnecessary for such a tiny project?

Maybe, but bugger writing actual CSS. Wanted to mess about with the styes so moving to Sass was a definite for me, probably got carried away with the Gulp file but gives the project a good base if anyone wanted to expand on it in future. Just messing about, nae hassle if it gets declined.

**Comment by DaftLimmy-zz** [comment]
Thanks but I don't know what Sass is or why you want to change it to it? Are you on commission? What's going on here?

**Comment by RyanDeegan** [comment]
> Thanks but I don't know what Sass is or why you want to change it to it? Are you on commission? What's going on here?

Haha, naw. I wanted to change the styles a bit and bring in some more modern layout styles with flexbox, but I've not written plain CSS in years so used Sass. Sass is a language that lets you use things like variables and functions, before it gets compiled to a CSS file which you can serve.

e.g. in my Sass file (with the use of a mixin):

```
.button {
    cursor: pointer;
    width: 100%;
    height: 100%;
    border: none;

    @include backgroundColor(1, #00ccff);
    @include backgroundColor(2, #ffff00);
    @include backgroundColor(3, #00ff00);
    @include backgroundColor(4, #fa0096);
    @include backgroundColor(5, #0f4295);
}
```
compiles to:

```
.button {
  cursor: pointer;
  width: 100%;
  height: 100%;
  border: none; }
  .button:nth-child(1) {
    background-color: #00ccff; }
    .button:nth-child(1):focus, .button:nth-child(1):active {
      outline: none;
      background-color: #00a3cc; }
  .button:nth-child(2) {
    background-color: #ffff00; }
    .button:nth-child(2):focus, .button:nth-child(2):active {
      outline: none;
      background-color: #cccc00; }
  .button:nth-child(3) {
    background-color: #00ff00; }
    .button:nth-child(3):focus, .button:nth-child(3):active {
      outline: none;
      background-color: #00cc00; }
  .button:nth-child(4) {
    background-color: #fa0096; }
    .button:nth-child(4):focus, .button:nth-child(4):active {
      outline: none;
      background-color: #c70077; }
  .button:nth-child(5) {
    background-color: #0f4295; }
    .button:nth-child(5):focus, .button:nth-child(5):active {
      outline: none;
      background-color: #0a2d67; }
```

Even without mixins etc., the nesting for hover states and media queries makes it nice to work with.

There's too many benefits of Sass to get into here but it's worth having a look into if you're gonna do much CSS in future. Give me a shout though if you take an interest in it and have any questions. I think most CSS devs will use either Less or Sass as a pre-processor to CSS (mostly Sass, I think).

https://sass-lang.com/documentation (I'm not on commission!).

**Pull request closed without merging**
