### PR TITLE
Complete cleanup and striped out reliance on createjs

### LINKED ISSUE #1: Works locally, but not on GitHub pages
I gave GitHub pages a shot, but it didn't work: https://daftlimmy.github.io/Swearing-Xylophone/

Any idea what's wrong? It's all relative paths, I thought that would work.

### PR DESCRIPTION
**Pull request by Harmelodic**
Instead just using vanilla JS with Audio API.
Fixes #1

### CODE REVIEW

**Comment by Harmelodic** [comment]
After merging, if you go to your project homepage, then Settings, then scroll down to GitHub Pages, then for Source: use `master` branch.

**Comment by Harmelodic** [comment]
Fixes #1

**Comment by DaftLimmy-zz** [comment]
Oh lovely, thanks.

But what about browsers that don't support .ogg? I see you've taken out the .mp3 alternative. Actually, what browsers don't support .mp3? Because I'd rather just use .mp3, it's easier to make.

And do these sounds preload like they do with createJS? Or am I stuck in the past and nobody needs to preload anything these days?

**Comment by Harmelodic** [comment]
MP3: https://caniuse.com/#feat=mp3
All browsers except Opera Mini support mp3 (but Opera Mini basically supports nothing).

OGG: https://caniuse.com/#feat=ogg-vorbis
Safari doesn't support OGG on either macOS or iOS, nor does Internet Explorer 11.

I hardcoded it to MP3 in the code, I just didn't delete the OGG files.

---

As for preloading, you can preload the audio files, if you instead using the `<audio>` tag and using the `preload` attribute.
HOWEVER, browsers can just ignore the preload if they want to (and in the quick test that I did, Chrome on macOS ignored 4 preloads) meaning that the audio file won't play unless you put in extra code in your `playSound()` function to check if the file is preloaded and if not, load the file and play it.

For a 4KB MP3 file that still loads pretty quickly on a slow 3G connection:
I don't think it's really worth it.

**Pull request merged**
